from enum import StrEnum


class Step(StrEnum):
    START = "START"
    AWAITING_LOCATION = "AWAITING_LOCATION"
    CONFIRM_STORE = "CONFIRM_STORE"
    CHOOSE_STORE = "CHOOSE_STORE"
    MANUAL_STORE_SELECTION = "MANUAL_STORE_SELECTION"
    AWAITING_PIN = "AWAITING_PIN"
    ASK_TRAFFIC = "ASK_TRAFFIC"
    ASK_GMV = "ASK_GMV"
    ASK_ONLINE_GMV = "ASK_ONLINE_GMV"
    ASK_ORDER = "ASK_ORDER"
    ASK_PIECES = "ASK_PIECES"
    ASK_NO_BUY_REASON = "ASK_NO_BUY_REASON"
    ASK_STOCK_ISSUE = "ASK_STOCK_ISSUE"
    ASK_NOTE = "ASK_NOTE"
    REVIEW_SUMMARY = "REVIEW_SUMMARY"
    CONFIRM_DUPLICATE = "CONFIRM_DUPLICATE"
    DONE = "DONE"


_NEXT_STEPS: dict[Step, Step] = {
    Step.START: Step.AWAITING_LOCATION,
    Step.ASK_TRAFFIC: Step.ASK_GMV,
    Step.ASK_GMV: Step.ASK_ONLINE_GMV,
    Step.ASK_ONLINE_GMV: Step.ASK_ORDER,
    Step.ASK_ORDER: Step.ASK_PIECES,
    Step.ASK_PIECES: Step.ASK_NO_BUY_REASON,
    Step.ASK_NO_BUY_REASON: Step.ASK_STOCK_ISSUE,
    Step.ASK_STOCK_ISSUE: Step.ASK_NOTE,
    Step.ASK_NOTE: Step.REVIEW_SUMMARY,
}


def next_step(step: Step) -> Step:
    return _NEXT_STEPS[step]
