from enum import StrEnum


class Step(StrEnum):
    START = "START"
    AWAITING_PHONE = "AWAITING_PHONE"
    ADMIN_MENU = "ADMIN_MENU"
    SUPER_ADMIN_MENU = "SUPER_ADMIN_MENU"
    MANAGE_USERS_MENU = "MANAGE_USERS_MENU"
    MANAGE_ADMINS_MENU = "MANAGE_ADMINS_MENU"
    USER_LIST = "USER_LIST"
    USER_DETAIL = "USER_DETAIL"
    USER_FORM_INPUT = "USER_FORM_INPUT"
    USER_EDIT_MENU = "USER_EDIT_MENU"
    USER_FORM_REVIEW = "USER_FORM_REVIEW"
    USER_CONFIRM_STATUS = "USER_CONFIRM_STATUS"
    USER_CONFIRM_RESET_LINK = "USER_CONFIRM_RESET_LINK"
    AWAITING_LOCATION = "AWAITING_LOCATION"
    CONFIRM_STORE = "CONFIRM_STORE"
    CHOOSE_STORE = "CHOOSE_STORE"
    MANUAL_STORE_SELECTION = "MANUAL_STORE_SELECTION"
    ASK_SALES_SOURCES = "ASK_SALES_SOURCES"
    ASK_SALES_INPUT = "ASK_SALES_INPUT"
    REVIEW_SALES_SUMMARY = "REVIEW_SALES_SUMMARY"
    EDIT_SALES_MENU = "EDIT_SALES_MENU"
    ASK_STOCK_ISSUE = "ASK_STOCK_ISSUE"
    ASK_NOTE = "ASK_NOTE"
    REVIEW_SUMMARY = "REVIEW_SUMMARY"
    CONFIRM_DUPLICATE = "CONFIRM_DUPLICATE"
    DONE = "DONE"


_NEXT_STEPS: dict[Step, Step] = {
    Step.START: Step.AWAITING_LOCATION,
    Step.ASK_STOCK_ISSUE: Step.ASK_NOTE,
    Step.ASK_NOTE: Step.REVIEW_SUMMARY,
}


def next_step(step: Step) -> Step:
    return _NEXT_STEPS[step]
