from enum import StrEnum


class Step(StrEnum):
    START = "START"
    AWAITING_LOCATION = "AWAITING_LOCATION"
    CONFIRM_STORE = "CONFIRM_STORE"
    CHOOSE_STORE = "CHOOSE_STORE"
    MANUAL_STORE_SELECTION = "MANUAL_STORE_SELECTION"
    AWAITING_PIN = "AWAITING_PIN"
    ASK_SALES_SOURCES = "ASK_SALES_SOURCES"
    ASK_SALES_INPUT = "ASK_SALES_INPUT"
    REVIEW_SALES_SUMMARY = "REVIEW_SALES_SUMMARY"
    EDIT_SALES_MENU = "EDIT_SALES_MENU"
    ASK_STOCK_ISSUE = "ASK_STOCK_ISSUE"
    ASK_NOTE = "ASK_NOTE"
    REVIEW_SUMMARY = "REVIEW_SUMMARY"
    CONFIRM_DUPLICATE = "CONFIRM_DUPLICATE"
    DONE = "DONE"


_NEXT_STEPS: dict[Step, Step] = {
    Step.START: Step.AWAITING_LOCATION,
    Step.ASK_STOCK_ISSUE: Step.ASK_NOTE,
    Step.ASK_NOTE: Step.REVIEW_SUMMARY,
}


def next_step(step: Step) -> Step:
    return _NEXT_STEPS[step]
